server {
    listen 80;

    # 1. Send normal traffic to the React frontend
    location / {
        proxy_pass http://client:3000;
    }

    # 2. Send /api/ traffic to the PHP backend
    location /api/ {
        fastcgi_pass server:9000;
        include fastcgi_params;
        # This tells PHP exactly which file to run to handle the API
        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
        fastcgi_param QUERY_STRING $query_string;
    }
}